-- EXPLORATORY DATA ANALYSIS
-- EXPLORE ALL OBJECTS IN THE DATABASE
SELECT *
FROM INFORMATION_SCHEMA.TABLES;

-- EXPLORE ALL COLUMNS IN THE DATABASE
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = ''
;

-- EXPLORE ALLL COUNTRIES OUR CUSTOMERS COME FROM
SELECT DISTINCT country
FROM gold.dim_customers;

-- Explore all categories "The Major Divisions"
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1,2,3;

-- Find the first and last date and range(In datediff you can calculate the years, months, weeks)
SELECT 
	MIN(order_date) as First_order, 
	MAX(order_date) as Last_order,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) as order_range_years
FROM gold.fact_sales;

-- Find the youngest and oldest customer and their age
SELECT 
	MIN(birthdate) as oldest,
	DATEDIFF(year, MIN(birthdate), GETDATE()) as oldest_age,
	MAX(birthdate) as youngest,
	DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age
FROM gold.dim_customers;

-- Find total sales
SELECT SUM(sales_amount) as Total_sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT
	SUM(quantity) as Total_quantity
FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) as Average_price
FROM gold.fact_sales;

-- Find the total number of orders 
SELECT COUNT(order_number) as Total_orders
FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) as Total_orders
FROM gold.fact_sales;

-- Find the total number of products
SELECT
	COUNT(product_name) as Total_number_products
FROM gold.dim_products;

-- Find the total number of customers
SELECT
	COUNT(customer_key) as Total_customers
FROM gold.dim_customers;

-- Find the total number of customers that have placed an order
SELECT
	COUNT (DISTINCT customer_key) as Number_of_customers_with_orders
FROM gold.fact_sales;

-- Generate a report that shows all the key metrics of the business
SELECT 'Total_sales' as Measure_name, SUM(sales_amount) as Measure_value
FROM gold.fact_sales
UNION ALL 
SELECT 'Total_quantity' as Measure_name, 
	SUM(quantity) as Measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Average_price' as Measure_name, AVG(price) as Measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Total_orders' as Measure_name, COUNT(DISTINCT order_number) as Measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Total_number_products' as Measure_name,
	COUNT(product_name) as Measure_value
FROM gold.dim_products
UNION ALL
SELECT 'Total_customers' as Measure_name,
	COUNT(customer_key) as Measure_value
FROM gold.dim_customers
UNION ALL
SELECT 'Number_of_customers_with_orders' as Measure_name,
	COUNT (DISTINCT customer_key) as Measure_value
FROM gold.fact_sales;

-- Find total customers by countries
SELECT 
	country, 
	COUNT(customer_key) as Total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_customers DESC;


-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) as Total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_customers DESC;

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) as Total_products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_products DESC;

-- What is the average costs in each category
SELECT
	category,
	AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category
SELECT 
	category,
	SUM(sales_amount) as Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON p.product_key = s.product_key
GROUP BY category
ORDER BY Total_revenue DESC;

-- Find total revenue generated by each customer
SELECT 
	c.customer_key, c.first_name, c.last_name,
	SUM(sales_amount) as Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name
ORDER BY Total_revenue DESC;

-- What is the distribution of sold items across countries
SELECT 
	c.country,
	SUM(s.quantity) as total_sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
	ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- Which 5 products generate the highest revenue
SELECT Top 5
	product_name,
	SUM(sales_amount) as Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON p.product_key = s.product_key
GROUP BY product_name
ORDER BY Total_revenue DESC;

SELECT *
FROM
(SELECT
	product_name,
	SUM(sales_amount) as Total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(sales_amount) DESC) as product_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON p.product_key = s.product_key
GROUP BY product_name) t
WHERE product_rank <= 5;

-- What are the 5 worst-performing products in terms of sales
SELECT Top 5
	product_name,
	SUM(sales_amount) as Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON p.product_key = s.product_key
GROUP BY product_name
ORDER BY Total_revenue ASC;

SELECT *
FROM
(SELECT
	product_name,
	SUM(sales_amount) as Total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(sales_amount) ASC) as product_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
	ON p.product_key = s.product_key
GROUP BY product_name) t
WHERE product_rank <= 5;

-- Find the top 10 customers who have generated the highest revenue
SELECT Top 10
	c.customer_key, c.first_name, c.last_name,
	SUM(sales_amount) as Total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name
ORDER BY Total_revenue DESC;

SELECT *
FROM(
	SELECT
	c.customer_key, c.first_name, c.last_name,
	SUM(sales_amount) as Total_revenue,
	RANK() OVER(ORDER BY SUM(sales_amount) DESC) as customer_rank
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name) cr
WHERE customer_rank <= 5;

-- The 3 customers with the fewest orders placed
SELECT Top 3
	c.customer_key, c.first_name, c.last_name,
	COUNT(DISTINCT order_number) as Total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
	ON c.customer_key = s.customer_key
GROUP BY c.customer_key, first_name, last_name
ORDER BY Total_orders ASC;

